# Revised for 0.48.0
opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - anyobject_protocol
  - attributes
  - balanced_xctest_lifecycle
  - capture_variable
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_subject
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - type_contents_order
  - typesafe_array_init
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Opt-in rules (which are disabled by default) are in this list to explicitly indicate that they should not be enabled.
disabled_rules:
  - array_init
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - expiring_todo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - file_header
  - file_name
  - file_types_order
  - large_tuple
  - missing_docs
  - nesting
  - no_extension_access_modifier
  - no_grouping_extension
  - object_literal
  - override_in_extension
  - prefer_self_in_static_references
  - prefixed_toplevel_constant
  - raw_value_for_camel_cased_codable_enum
  - required_deinit
  - required_enum_case
  - strict_fileprivate
  - todo
  - trailing_closure
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

closure_body_length:
  warning: 80
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 20

file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

force_cast: warning

force_try: warning

force_unwrapping: error

function_body_length:
  warning: 100
  error: 120

identifier_name:
  excluded:
    - i
    - id
    - ID
    - x
    - y
    - h1
    - h2
    - h3
    - h4
    - h5
    - h6

line_length:
  warning: 120
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400
