name: Build and test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build_and_lint:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Install Bundler
        run: gem install bundler -v 2.4.7

      - name: Install gems
        run: bundle install

      - name: Build
        run: bundle exec fastlane build build_configuration:development
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}

      - name: Setup Mint Swift Package Manager
        uses: irgaly/setup-mint@v1.1.1

      - name: Test
        run: bundle exec fastlane tests